# SteeltoeOSS/Samples Azure DevOps pipeline

trigger:
- devops-spike

jobs:
- job: Spike
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: UseDotNet@2
    displayName: 'Use DotNet 2.2.x'
    inputs:
      packageType: sdk
      version: 2.2.x
  - script: dotnet --version
    displayName: 'Display dotnet version'
