parameters:
  feature: ''
  sample: ''
jobs:
- job: ${{parameters.feature}}_${{parameters.sample}}_Linux
  displayName: '${{parameters.feature}}: ${{parameters.sample}} (Linux)'
  pool:
    vmImage: Ubuntu-16.04
  steps:
  - template: setup-behave-linux-steps.yml
  - template: setup-dotnet2-steps.yml
  - template: setup-cloud-foundry-cli-linux-steps.yml
  - script: behave ${{parameters.feature}}/src/AspDotNetCore/${{parameters.sample}}
    displayName: 'Test -> ${{parameters.feature}}: ${{parameters.sample}}'
  - template: publish-results-steps.yml
    parameters:
      os: Linux
- job: ${{parameters.feature}}_${{parameters.sample}}_OSX
  displayName: '${{parameters.feature}}: ${{parameters.sample}} (OSX)'
  pool:
    vmImage: MacOS-10.14
  steps:
  - template: setup-behave-osx-steps.yml
  - template: setup-dotnet2-steps.yml
  - template: setup-cloud-foundry-cli-osx-steps.yml
  - script: behave ${{parameters.feature}}/src/AspDotNetCore/${{parameters.sample}}
    displayName: 'Test -> ${{parameters.feature}}: ${{parameters.sample}}'
  - template: publish-results-steps.yml
    parameters:
      os: OSX
- job: ${{parameters.feature}}_${{parameters.sample}}_Windows
  displayName: '${{parameters.feature}}: ${{parameters.sample}} (Windows)'
  pool:
    vmImage: Windows-2019
  steps:
  - template: setup-behave-windows-steps.yml
  - template: setup-dotnet2-steps.yml
  - template: setup-cloud-foundry-cli-windows-steps.yml
  - script: behave ${{parameters.feature}}/src/AspDotNetCore/${{parameters.sample}}
    displayName: 'Test -> ${{parameters.feature}}: ${{parameters.sample}}'
  - template: publish-results-steps.yml
    parameters:
      os: Windows
