steps:
- bash: |
    cat >> user.ini << EOF
    max_attempts = $STEELTOE_MAX_ATTEMPTS
    cf_apiurl = $STEELTOE_CF_APIURL
    cf_org = $STEELTOE_CF_ORG
    cf_username = $STEELTOE_CF_USERNAME
    cf_password = $STEELTOE_CF_PASSWORD
    cf_max_attempts = $STEELTOE_CF_MAX_ATTEMPTS
    EOF
    cat user.ini
  env:
    STEELTOE_CF_USERNAME: $(steeltoe.cf.username)
    STEELTOE_CF_PASSWORD: $(steeltoe.cf.password)
  displayName: 'Configure Behave'
- powershell: |
    Get-Content user.ini
# steps:
# - powershell: |
#     Add-Content user.ini "max_attempts = $Env:STEELTOE_MAX_ATTEMPTS"
#     Add-Content user.ini "cf_apiurl = $Env:STEELTOE_CF_APIURL"
#     Add-Content user.ini "cf_org = $Env:STEELTOE_CF_ORG"
#     Add-Content user.ini "cf_username = $Env:STEELTOE_CF_USERNAME"
#     Add-Content user.ini "cf_password = $Env:STEELTOE_CF_PASSWORD"
#     Add-Content user.ini "cf_max_attempts = $Env:STEELTOE_CF_MAX_ATTEMPTS"
#     Get-Content user.ini
#   env:
#     STEELTOE_CF_USERNAME: $(steeltoe.cf.username)
#     STEELTOE_CF_PASSWORD: $(steeltoe.cf.password)
#   displayName: 'Configure Behave'
