# SteeltoeOSS/Samples Azure DevOps pipeline

trigger:
- devops-spike

jobs:
- job: Spike
  pool:
    vmImage: 'Windows-2019'
  # pool:
    # vmImage: 'Ubuntu-16.04'
  steps:
  - template: tasks/setup-dotnet2.2.yml
  - template: tasks/setup-behave.yml
