# SteeltoeOSS/Samples Azure DevOps pipeline

trigger:
- devops-spike

jobs:
- job: Spike_DotNet22_Windows2019
  pool:
    vmImage: 'Windows-2019'
  steps:
  - template: tasks/setup-dotnet2.2.yml
  - template: tasks/setup-behave.yml
- job: Spike_DotNet22_Ubuntu1604
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: tasks/setup-dotnet2.2.yml
  - template: tasks/setup-behave.yml
- job: Spike DotNet22 MacOS10.14
  pool:
    vmImage: 'MacOS-10.14'
  steps:
  - template: tasks/setup-dotnet2.2.yml
  - template: tasks/setup-behave.yml
