# SteeltoeOSS/Samples Azure DevOps pipeline

trigger:
- devops-spike

jobs:
- job: Spike_DotNet22_Windows19
  pool:
    vmImage: 'Windows-2019'
  steps:
  - template: tasks/setup-dotnet2.2.yml
  # - template: tasks/setup-behave.yml
- job: Spike_DotNet22_Ubuntu16
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - template: tasks/setup-dotnet2.2.yml
  # - template: tasks/setup-behave.yml
