# SteeltoeOSS/Samples Azure DevOps pipeline

trigger:
- devops-spike

jobs:

# Configuration:CloudFoundry

- job: Configuration_CloudFoundry_DotNet22_Windows
  pool:
    vmImage: 'Windows-2019'
  steps:
  # - template: templates/setup-behave.yml
  # - template: templates/setup-dotnet2.2.yml
  # - template: templates/setup-cloudfoundry.yml
  # - script: behave Configuration/src/AspDotNetCore/CloudFoundry
    # displayName: 'Sample Configuration:CloudFoundry'
  # - template: templates/publish-results.yml
  - powershell: |
      Write-Host "[behave.userdata]"
      Write-Host "cf_apiurl = api.run.pcfone.io"
      Write-Host "cf_org = group-steeltoe"
      Write-Host "cf_username = $Env.STEELTOE_CF_USERNAME"
      Write-Host "cf_password ="
      Write-Host "cf_max_attempts = "
    env:
      CF_STEELTOE_USERNAME: $(steeltoe.cf.username)
    # Add-Content behave.ini "[behave.userdata]
    # Add-Content behave.ini "cf_apiurl = api.run.pcfone.io
    # Add-Content behave.ini "cf_org = group-steeltoe
    # Add-Content behave.ini "cf_username =
    # Add-Content behave.ini "cf_password =
    # Add-Content behave.ini "cf_max_attempts = "

# Configuration:Simple

# - job: Configuration_Simple_DotNet22_Windows
#   pool:
#     vmImage: 'Windows-2019'
#   steps:
#   - template: templates/setup-behave.yml
#   - template: templates/setup-dotnet2.2.yml
#   - template: templates/setup-java8.yml
#   - script: behave Configuration/src/AspDotNetCore/Simple
#     displayName: 'Test Configuration:Simple'
# - job: Configuration_Simple_DotNet22_Linux
#   pool:
#     vmImage: 'Ubuntu-16.04'
#   steps:
#   - template: templates/setup-behave.yml
#   - template: templates/setup-dotnet2.2.yml
#   - template: templates/setup-java8.yml
#   - script: behave Configuration/src/AspDotNetCore/Simple
# - job: Configuration_Simple_DotNet22_OSX
#   pool:
#     vmImage: 'MacOS-10.14'
#   steps:
#   - template: templates/setup-behave.yml
#   - template: templates/setup-dotnet2.2.yml
#   - template: templates/setup-java8.yml
#   - script: behave Configuration/src/AspDotNetCore/Simple
