# =============================================================================
# SteeltoeOSS/Samples Azure DevOps pipeline
# =============================================================================

trigger:
- devops-spike

jobs:

  # ---------------------------------------------------------------------------
  # Configuration: CloudFoundry
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Configuration
    sample: CloudFoundry
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Configuration
    sample: CloudFoundry
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Configuration
    sample: CloudFoundry
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Configuration: Simple
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Configuration
    sample: Simple
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Configuration
    sample: Simple
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Configuration
    sample: Simple
    dotnetVersion: 2.2

# - job: Configuration_Simple_DotNet22_Windows
#   displayName: 'Configuration: Simple (DotNet 2.2/Windows)'
#   pool:
#     vmImage: 'Windows-2019'
#   steps:
#   - template: templates/setup-behave.yml
#   - template: templates/setup-dotnet2.2.yml
#   - template: templates/setup-java8.yml
#   - script: behave Configuration/src/AspDotNetCore/Simple
#     displayName: 'Configuration: Simple'
#   - template: templates/publish-results.yml

  # ---------------------------------------------------------------------------
  # Configuration: SimpleCloudFoundry
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Configuration
    sample: SimpleCloudFoundry
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Configuration
    sample: SimpleCloudFoundry
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Configuration
    sample: SimpleCloudFoundry
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Connectors: MySql
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Connectors
    sample: MySql
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Connectors
    sample: MySql
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Connectors
    sample: MySql
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Connectors: MySqlEF6
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Connectors
    sample: MySqlEF6
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Connectors
    sample: MySqlEF6
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Connectors
    sample: MySqlEF6
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Connectors: MySqlEFCore
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Connectors
    sample: MySqlEFCore
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Connectors
    sample: MySqlEFCore
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Connectors
    sample: MySqlEFCore
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Connectors: PostgreSql
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Connectors
    sample: PostgreSql
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Connectors
    sample: PostgreSql
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Connectors
    sample: PostgreSql
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Connectors: PostgreEFCore
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Connectors
    sample: PostgreEFCore
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Connectors
    sample: PostgreEFCore
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Connectors
    sample: PostgreEFCore
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Connectors: RabbitMQ
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Connectors
    sample: RabbitMQ
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Connectors
    sample: RabbitMQ
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Connectors
    sample: RabbitMQ
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Connectors: Redis
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Connectors
    sample: Redis
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Connectors
    sample: Redis
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Connectors
    sample: Redis
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Connectors: SqlServerEFCore
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Connectors
    sample: SqlServerEFCore
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Connectors
    sample: SqlServerEFCore
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Connectors
    sample: SqlServerEFCore
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Management: CloudFoundry
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Management
    sample: CloudFoundry
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Management
    sample: CloudFoundry
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Management
    sample: CloudFoundry
    dotnetVersion: 2.2

  # ---------------------------------------------------------------------------
  # Security: CloudFoundrySingleSignon
  # ---------------------------------------------------------------------------

- template: templates/cloud-foundry-linux.yml
  parameters:
    group: Security
    sample: CloudFoundrySingleSignon
    dotnetVersion: 2.2

- template: templates/cloud-foundry-osx.yml
  parameters:
    group: Security
    sample: CloudFoundrySingleSignon
    dotnetVersion: 2.2

- template: templates/cloud-foundry-windows.yml
  parameters:
    group: Security
    sample: CloudFoundrySingleSignon
    dotnetVersion: 2.2
