# SteeltoeOSS/Samples Azure DevOps pipeline

trigger:
- devops-spike

jobs:
- job: Configuration_Simple_DotNet22_Windows
  pool:
    vmImage: 'Windows-2019'
  steps:
  - template: tasks/setup-dotnet2.2.yml
  - template: tasks/setup-behave.yml
  - script: behave Configuration/src/AspDotNetCore/Simple
# - job: Spike_DotNet22_Linux
#   pool:
#     vmImage: 'Ubuntu-16.04'
#   steps:
#   - template: tasks/setup-dotnet2.2.yml
#   - template: tasks/setup-behave.yml
# - job: Spike_DotNet22_MacOS
#   pool:
#     vmImage: 'MacOS-10.14'
#   steps:
#   - template: tasks/setup-dotnet2.2.yml
#   - template: tasks/setup-behave.yml
